#!/bin/bash
set -e

# Supertokens user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $SUPERTOKENS_POSTGRES_USER WITH PASSWORD '$SUPERTOKENS_POSTGRES_PASSWORD';
    CREATE DATABASE $SUPERTOKENS_POSTGRES_DB;
    ALTER DATABASE $SUPERTOKENS_POSTGRES_DB OWNER TO $SUPERTOKENS_POSTGRES_USER;
EOSQL
